### ISSUE TITLE
fcns of arrays

### ISSUE THREAD

**Issue by vgupta1** [julian-gehring/Bootstrap.jl#2]
I'd like to be able to use boot with array data, not just vectors, something like:
``` julia
dat = randn(5000, 3) #observations by row
muhat = mean(dat, 1)
f(boot_sample) = norm(mean(boot_sample) - muhat)

boot(dat, f, 100)
```
Unfortunately, boot is only defined for data which is an abstract vector.  Is there a fast way to change my data to a vector of vectors?  Would ideally want to do it "in place" to save on the memory, too.

Even better, it feels like this sort of functionality should be generically supported by the package, somehow...  Thoughts?

**Comment by julian-gehring** [comment]
This will take longer than I expected since I have to address some namespace issues first.

**Comment by julian-gehring** [comment]
@vgupta1 I add support for multi-dimensional arrays for the basic bootstrap, see the commit 717647f66bf39149dbb98497750602bafdc5190c. You can give it a first test, e.g.

```{julia}
dat = randn(100, 3)
mu_hat = mean(dat, 1)
fun_array(x::AbstractArray) = norm(mean(x) - mu_hat)

bs1 = boot_basic(dat, fun_array, nSamples)
ci_bs1 = ci_perc(bs1)
```

Let me know if this behaves as expected. I'll add support for the other bootstrap methods soon.

**Comment by vgupta1** [comment]
Thanks, Julian.  I'll find time to take a careful look soon.  At first
glance though, it looks like this implementation does a memory alloc every
iteration for the bootstrap indices.  (similar ot my last PR for the
unidimensional case).  It'd be nicer to reuse the same memory space each
iteration, if at all possible.  I can also tackle this myself when I look
at it if you prefer.

VG

**Comment by julian-gehring** [comment]
I'll optimize this in any way, the current implementation has room for improvement. At the moment, it would be good to know if it is sufficient for the analysis you have in mind.

**Comment by julian-gehring** [comment]
To clarify, I mean if the interface and functionality works for you. I would like to make sure, it behaves for Arrays the way it should. Then I can go ahead, add support for the other methods, together with optimizations of the code.

**Comment by vgupta1** [comment]
Understood.  I'll take a look ASAP.

VG

**Comment by vgupta1** [comment]
Hi Julian

This works exactly as I'd expect, thanks!

As a side note: I did a rough speed comparison to a knocked-up version i
have that avoids the copy, and the speed difference is substantial in this
multidimensional case.

Vishal

**Comment by julian-gehring** [comment]
Thanks for checking, it's always good to have a second pair of eyes looking at it.

968af5dcc2675333544b555125d017af98a9e9cb has an improved version of the basic bootstrap for arrays, which does a inplace sampling of the index variable. This decreases the memory allocation and makes for a slightly better runtime. However, the main bottleneck is `slicedim`operation on the array. I'll look into this. If you have a smart idea about this...

**Comment by julian-gehring** [comment]
86e764e88e1a2f8cb44f901f02ba87a15a3bcdbf has two boot_basic implementations with a low-memory footprint: `boot_basic_lm` and `boot_basic_lm2`, both are not exported. For large arrays, the memory usage is reduced by orders of magnitude, with an increase of runtime of about a factor of 2 (at least for my test cases).

**Comment by julian-gehring** [comment]
With da7ad8a2be44f4ed00f763e9279549078b696755, all bootstrap methods support multi-dimensional arrays. I'll add memory optimized versions as part of a general refractoring soon.
